export const SEARCH_RECIPES = 'SEARCH_RECIPES';

export const ADD_RECIPE = 'ADD_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const FILTER_RECIPE = 'FILTER_RECIPE';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const GET_RECIPES = 'GET_RECIPES';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_LOADING = 'SET_LOADING';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CONTACT_ERROR = 'CONTACT_ERROR';
export const GET_ONE_RECIPE = 'GET_ONE_RECIPE';
export const GET_MY_RECIPES = 'GET_MY_RECIPES';
export const ADD_USER_RESTRICTIONS = 'ADD_USER_RESTRICTIONS';
